spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: mynacos-server.com:8848

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
